// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v4.25.3
// source: schema/message.schema.proto

package schema

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SunTerraDeviceMessage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name     string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Username string `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status   int64  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
}

func (x *SunTerraDeviceMessage) Reset() {
	*x = SunTerraDeviceMessage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_schema_message_schema_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SunTerraDeviceMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SunTerraDeviceMessage) ProtoMessage() {}

func (x *SunTerraDeviceMessage) ProtoReflect() protoreflect.Message {
	mi := &file_schema_message_schema_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SunTerraDeviceMessage.ProtoReflect.Descriptor instead.
func (*SunTerraDeviceMessage) Descriptor() ([]byte, []int) {
	return file_schema_message_schema_proto_rawDescGZIP(), []int{0}
}

func (x *SunTerraDeviceMessage) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SunTerraDeviceMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SunTerraDeviceMessage) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

var File_schema_message_schema_proto protoreflect.FileDescriptor

var file_schema_message_schema_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x2e, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x61, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x02, 0x70,
	0x62, 0x22, 0x5f, 0x0a, 0x15, 0x53, 0x75, 0x6e, 0x54, 0x65, 0x72, 0x72, 0x61, 0x44, 0x65, 0x76,
	0x69, 0x63, 0x65, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x42, 0x2e, 0x5a, 0x2c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x73, 0x74, 0x61, 0x72, 0x52, 0x4d, 0x53, 0x2f, 0x70, 0x75, 0x62, 0x73, 0x75, 0x62, 0x2d,
	0x78, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x66, 0x2f, 0x73, 0x63, 0x68, 0x65,
	0x6d, 0x61, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_schema_message_schema_proto_rawDescOnce sync.Once
	file_schema_message_schema_proto_rawDescData = file_schema_message_schema_proto_rawDesc
)

func file_schema_message_schema_proto_rawDescGZIP() []byte {
	file_schema_message_schema_proto_rawDescOnce.Do(func() {
		file_schema_message_schema_proto_rawDescData = protoimpl.X.CompressGZIP(file_schema_message_schema_proto_rawDescData)
	})
	return file_schema_message_schema_proto_rawDescData
}

var file_schema_message_schema_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_schema_message_schema_proto_goTypes = []interface{}{
	(*SunTerraDeviceMessage)(nil), // 0: pb.SunTerraDeviceMessage
}
var file_schema_message_schema_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_schema_message_schema_proto_init() }
func file_schema_message_schema_proto_init() {
	if File_schema_message_schema_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_schema_message_schema_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SunTerraDeviceMessage); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_schema_message_schema_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schema_message_schema_proto_goTypes,
		DependencyIndexes: file_schema_message_schema_proto_depIdxs,
		MessageInfos:      file_schema_message_schema_proto_msgTypes,
	}.Build()
	File_schema_message_schema_proto = out.File
	file_schema_message_schema_proto_rawDesc = nil
	file_schema_message_schema_proto_goTypes = nil
	file_schema_message_schema_proto_depIdxs = nil
}
